---
title: "EP08-respuesta-equipo-3"
author: "Equipo 3"
date: "2024-11-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
datos <- read.csv('EP08 Datos CASEN 2017.csv')
```

# Pregunta 1

# Pregunta 2

Se desea conocer si es que el ingreso per cápita promedio es similar para las personas de sexo Hombre, entre las diferentes comunas de la zona oriente de Santiago ("Providencia", "Ñuñoa", "La Reina", "Las Condes", "Vitacura", "Lo Barnechea")

```{r}
Hombres <- datos %>%
  filter(sexo == "Hombre")

providencia <- Hombres %>%
  filter(comuna == "Providencia") %>%
  distinct(id.vivienda, .keep_all = TRUE) %>%
  sample_n(size=250) %>%
  select(ytot)

nunoa <- Hombres %>%
  filter(comuna == "Ñuñoa") %>%
  distinct(id.vivienda, .keep_all = TRUE) %>%
  sample_n(size=250) %>%
  select(ytot)

laReina <- Hombres %>%
  filter(comuna == "Providencia") %>%
  distinct(id.vivienda, .keep_all = TRUE) %>%
  sample_n(size=250) %>%
  select(ytot)

lasCondes <- Hombres %>%
  filter(comuna == "Providencia") %>%
  distinct(id.vivienda, .keep_all = TRUE) %>%
  sample_n(size=250) %>%
  select(ytot)

vitacura <- Hombres %>%
  filter(comuna == "Providencia") %>%
  distinct(id.vivienda, .keep_all = TRUE) %>%
  sample_n(size=250) %>%
  select(ytot)

loBarnechea <- Hombres %>%
  filter(comuna == "Providencia") %>%
  distinct(id.vivienda, .keep_all = TRUE) %>%
  sample_n(size=250) %>%
  select(ytot)

```

Para ello,

```{r}

#Pregunta 1: ¿Es similar la proporcion entre mujeres y hombres viudos en los hogares de la comuna de san Joaquín, en la Region Metropolitana?

hombres_hogar_sample <- Hombres %>%
  filter(comuna == "San Joaquín") %>%
  distinct(id.vivienda, .keep_all = T) %>%
  select(id.vivienda, sexo, ecivil) %>%
  
  sample_n()
  

mujeres_hogar <- datos %>%
  filter(comuna == "San Joaquín" & sexo == "Mujer") %>%
  distinct(id.vivienda, .keep_all = T)
```

